#pragma config(Sensor, dgtl1,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl11, right,          sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           forearm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           launcher1,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, dgtl1,  rightin,        sensorQuadEncoder)
//#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
//#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port4,           launcher1,     tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port6,           motor6,        tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  portz10,           ,             tmotorVex393_HBridge, openLoop)



//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//#pragma config(Motor,  port8,           arm_motor,     tmotorVex393_MC29, openLoop)
// This code is for the VEX cortex platform


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/


task main()
{
	// ..........................................................................
	// Insert user code here.
	while( 1 == 1) {
		if ( vexRT[Btn5U] == 1 ) {
			//Code BLUE

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]<1400){
				motor[port1] = 127;
				motor[port2] = -127;
				motor[port3] = -127;
				motor[port5] = 127;
			}
			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]>-740){
				motor[port1] = -127;
				motor[port2] = 127;
				motor[port3] = 127;
				motor[port5] = -127;
		  }
		  motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port5] = 0;

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]>-260){
				motor[port1] = 127;
				motor[port2] = 127;
				motor[port3] = 127;
				motor[port5] = 127;
		  }
		  motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port5] = 0;

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]>-90){
				motor[port1] = -127;
				motor[port2] = 127;
				motor[port3] = 127;
				motor[port5] = -127;
		  }
		  motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port5] = 0;



			motor[port10] = 127;
			wait1Msec(1000);
			motor[port10] = 0;



			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]< 600){
				motor[port1] = 127;
				motor[port2] = -127;
				motor[port3] = -127;
				motor[port5] = 127;
		  }
		  motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port5] = 0;



			motor[port10] = -90;
			wait1Msec(1600);
			motor[port10] = 0;

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]<90){
				motor[port1] = -127;
				motor[port2] = -127;
				motor[port3] = -127;
				motor[port5] = -127;
		  }
		  SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]<900){
				motor[port1] = 127;
				motor[port2] = -127;
				motor[port3] = -127;
				motor[port5] = 127;
			}

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]>-740){
				motor[port1] = -127;
				motor[port2] = 127;
				motor[port3] = 127;
				motor[port5] = -127;
		  }


		//Code RED
			/*
			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]<1400){
				motor[port1] = 127;
				motor[port2] = -127;
				motor[port3] = -127;
				motor[port5] = 127;
			}
			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]>-610){
				motor[port1] = -127;
				motor[port2] = 127;
				motor[port3] = 127;
				motor[port5] = -127;
		  }
		  motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port5] = 0;

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]<160){
				motor[port1] = -127;
				motor[port2] = -127;
				motor[port3] = -127;
				motor[port5] = -127;
		  }
		  motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port5] = 0;

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]>-100){
				motor[port1] = -127;
				motor[port2] = 127;
				motor[port3] = 127;
				motor[port5] = -127;
		  }
		  motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port5] = 0;



			motor[port10] = 127;
			wait1Msec(1000);
			motor[port10] = 0;



			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]< 800){
				motor[port1] = 127;
				motor[port2] = -127;
				motor[port3] = -127;
				motor[port5] = 127;
		  }
		  motor[port1] = 0;
			motor[port2] = 0;
			motor[port3] = 0;
			motor[port5] = 0;



			motor[port10] = -90;
			wait1Msec(1700);
			motor[port10] = 0;

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]>-140){
				motor[port1] = 127;
				motor[port2] = 127;
				motor[port3] = 127;
				motor[port5] = 127;
			}

			SensorValue[left] = 0;
			SensorValue[right] = 0;
			while(SensorValue[left]<500){
				motor[port1] = 127;
				motor[port2] = -127;
				motor[port3] = -127;
				motor[port5] = 127;
				*/
		/*
		}
		elif (vexRT[Btn6U] == 1){
			int a = (-(vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch3Xmtr2] + vexRT[Ch4Xmtr2])*0.85);
		int b = (-(vexRT[Ch3]*-1 + vexRT[Ch4] + vexRT[Ch3Xmtr2]*-1 + vexRT[Ch4Xmtr2])*0.85);
		if (vexRT[Btn8L]==1&&prestate1==0){
			if (ts==1) ts = 0;
			else ts = 1;
			prestate1 = 1;
		}
		if (vexRT[Btn8L] ==0 &&prestate1==1){
			prestate1 = 0;
		}
		if (ts==1){
			motor[port3] = a;
			motor[port2] = a;

			motor[port1] = b;
			motor[port5] = b;
		}
		else{
			motor[port3] = b;
			motor[port2] = b;

			motor[port1] = a;
			motor[port5] = a;
		}



		//port 4 connected to motor 7 and 8
		//port 5 connected to motor 9 and 10
		if (vexRT[Btn5D]==0){
			preState = 0;
		}

		if (vexRT[Btn5D] == 1 && preState ==0){
			preState = 1;
			state = state == 0? 1:0;
		}
		motor[launcher1] = state*-127;



		//motor[port6] = vexRT[Btn8D]==1? -127:0;
		//motor[port6] = vexRT[Btn8U]==1? 127:0;
		motor[port6] = 0;

		if (vexRT[Btn8D] == 1){
			motor[port10] = 90;
		}
		//sauce thing flipper
		else if (vexRT[Btn8U] == 1){
			motor[port10] = -90;
		}
		else if (vexRT[Btn8D] == 0 && vexRT[Btn8U] == 0){
			motor[port10] = 0;
		}



		motor[arm] = -vexRT[Ch2];



		motor[forearm] = -8;
		if (vexRT[Btn7U] == 1){
			motor[forearm] = -;
			motor[forearm] = 90;

		}


		}
		*/
	}
	}

}
