#pragma config(Motor,  port5,           whatever,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void do_nothing(int a){
	if (a == 1){
		motor[whatever] = -128;
		}
	else{
		motor[whatever] = 0;
	}
return;
}

task main()
{
	int a = 0;
while (1 < 2){
	a = vexRT[Btn7L];
do_nothing(a);
}


}
