#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           right2,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int state = 0;
	while (true){

		int a = -(vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch3Xmtr2] + vexRT[Ch4Xmtr2]);
		int b =  -(vexRT[Ch3]*-1 + vexRT[Ch4] + vexRT[Ch3Xmtr2]*-1 + vexRT[Ch4Xmtr2]);


		motor[left] = a;
		motor[left2] = a;
		motor[right] = b;
		motor[right2] = b;

		if (state == 0 && vexRT[Btn7D] == 1){
			motor[intake] = motor[intake]==80? 0:80;
			state = 1;
			}else if (state == 1 &&  vexRT[Btn7D] == 0){
			state = 0;
		}
	}
}
