#pragma config(Sensor, dgtl1,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl11, right,          sensorQuadEncoder)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           forearm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           launcher1,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, dgtl1,  rightin,        sensorQuadEncoder)
//#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
//#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port4,           launcher1,     tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port6,           motor6,        tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)



//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//#pragma config(Motor,  port8,           arm_motor,     tmotorVex393_MC29, openLoop)
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void run(float coef = 1){
	motor[port2] = 127*coef;
	motor[port3] = 127*coef;
	motor[port4] = -127*coef;
	motor[port5] = -127*coef;
}
void runslow(int displace){
	motor[port2] = 100;
	motor[port3] = 100;
	motor[port4] = -100;
	motor[port5] = -100;
}
void reverse(float coef = 1){
	motor[port2] = -127*coef;
	motor[port3] = -127*coef;
	motor[port4] = 127*coef;
	motor[port5] = 127*coef;
}
void pause(){
	motor[port2] = 0;
	motor[port3] = 0;
	motor[port4] = 0;
	motor[port5] = 0;
}
void collector(bool on = true){
	int mode = 1;
	if (on){
		mode = 1;
	}
	else{
		mode = 0;
	}
	motor[port6] = 127*mode;
}

void move_foward(int displace,float speed = 1){

	while(SensorValue[right]<displace){

		run(speed);
	}
	pause();
}

void move_reverse(int displace,float speed = 1){

	while(SensorValue[right]>displace){
		reverse(speed);
	}
	pause();
}
void turn(int angle){
	while(SensorValue[right]<(angle*0.5)){
		motor[port2] = 40;
		motor[port3] = 40;
		motor[port4] = 40;
		motor[port5] = 40;
	}
	pause();
}
void rturn(int angle){
	while(SensorValue[right]>-(angle*0.5)){
		motor[port2] = -60;
		motor[port3] = -60;
		motor[port4] = -60;
		motor[port5] = -60;
	}
	pause();
}

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{


	//SensorValue[left] = 0;
	//while(SensorValue[left]>1400){
	//	motor[port2] = 127;
	//	motor[port3] = 127;
	//	motor[port4] = -127;
	//	motor[port5] = -127;
	//}
	//SensorValue[left] = 0;
	//while(SensorValue[left]>-1400){
	//	motor[port2] = -127;
	//	motor[port3] = -127;
	//	motor[port4] = 127;
	//	motor[port5] = 127;
	// }


	// motor[port2] = 127;
	// motor[port3] = 127;
	//motor[port4] = 127;
	//motor[port5] = 127;
	//wait1Msec(100);
	//motor[port2] = 0;
	// motor[port3] = 0;
	//motor[port4] = 0;
	//motor[port5] = 0;
	//motor[port6] = 127;
	//	wait1Msec(3000);
	//	motor[port6] = 0;
	//motor[port2] = -127;
	// motor[port3] = -127;
	//motor[port4] = -127;
	//motor[port5] = -127;
	//wait1Msec(100);
	//motor[port2] = 0;
	// motor[port3] = 0;
	//motor[port4] = 0;
	//motor[port5] = 0;

	//	SensorValue[left] = 0;
	//while(SensorValue[left]>-9000){
	//	motor[port2] = 127;
	//	motor[port3] = 127;
	//	motor[port4] = -127;
	//	motor[port5] = -127;
	// }
	// SensorValue[left] = 0;
	// while(SensorValue[left]>-160){
	//  motor[port2] = 127;
	//	motor[port3] = 127;
	//	motor[port4] = 127;
	//	motor[port5] = 127;
	//}
	//wait1Msec(1000);
	// motor[port2] = 0;
	//motor[port3] = 0;
	//motor[port4] = 0;
	//motor[port5] = 0;



}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task usercontrol()
{

	//// User ontrol code here, inside the loop

	// This is the main execution loop for the user control program.
	// Each time through the loop your program should update motor + servo
	// values based on feedback from the joysticks.

	// ........................................................................
	// Insert user code here. This is where you use the joystick values to
	// update your motors, etc.
	// ........................................................................

	int state=0, preState=0;
	int ts = 1, prestate1 = 0;

	//int initial_sensor = SensorValue[rightin];
	while(1==1){
		//DRIVING///////////////////////////////////////////////////////////////////
		int a = -(vexRT[Ch3] + vexRT[Ch4]*0.8 + vexRT[Ch3Xmtr2] + vexRT[Ch4Xmtr2]*0.8);
		int b =  -(vexRT[Ch3]*-1 + vexRT[Ch4]*0.8 + vexRT[Ch3Xmtr2]*-1 + vexRT[Ch4Xmtr2]*0.8);
		if (vexRT[Btn8L]==1&&prestate1==0){
			if (ts==1) ts = 0;
			else ts = 1;
			prestate1 = 1;
		}
		if (vexRT[Btn8L] ==0 &&prestate1==1){
			prestate1 = 0;
		}
		if (ts==1){
			motor[port3] = b;
			motor[port2] = b;

			motor[port4] = a;
			motor[port5] = a;
		}
		else{
			motor[port3] = a;
			motor[port2] = a;

			motor[port4] = b;
			motor[port5] = b;
		}



		//port 4 connected to motor 7 and 8
		//port 5 connected to motor 9 and 10



		if (vexRT[Btn5D]==0){
			preState = 0;
		}

		if (vexRT[Btn5D] == 1 && preState ==0){
			preState = 1;
			state = state == 0? 1:0;
		}
		if (vexRT[Btn5U] == 1){
			motor[launcher1] = -80;
		}
		else{
			motor[launcher1] = state*127;
		}






		//motor[port6] = vexRT[Btn8D]==1? -127:0;
		//motor[port6] = vexRT[Btn8U]==1? 127:0;
		motor[port6] = 0;
		if (vexRT[Btn8U] == 1){
			motor[port6] = -127;
		}

		//sauce thing flipper
		if (vexRT[Btn8D] == 1){
			motor[port6] = 127;

		}





		motor[arm] = -vexRT[Ch2];



		if (vexRT[Btn7U] == 1){
			motor[forearm] = -80;
		}

		//sauce thing flipper
		else if (vexRT[Btn7D] == 1){
			motor[forearm] = 60;

		}
		else{

			motor[forearm] = -8;
		}




		//motor[forearm] = -vexRT[Ch2]-15;


	}

}
