#pragma config(Sensor, in1,    p,              sensorPotentiometer)
#pragma config(Motor,  port1,            ,             tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,            ,             tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int state=0, preState=0;
	int ts = 1, prestate1 = 0;
	SensorValue[p] = 0;
	int thr = 600;
	int angle = 0;
	bool punch = false;

	while (true){
		angle = 0;
		if (vexRT[Btn5D] == 1){
			angle = 1400;
			punch = true;
		}

		else if (vexRT[Btn5U] == 1){
			angle = 4000;
			punch = true;
		}
		else{
			angle = 0;
			punch = false;
		}

		if (angle !=0){
			if (abs(SensorValue[p]-angle)>30){
				if (abs(SensorValue[p]-angle)<thr){
					if (SensorValue[p]-angle<thr){
						motor[port2] = 10;

					}
					else if (SensorValue[p]-angle>-thr){
						motor[port2] = -10;

					}

				}
				else{
					if (SensorValue[p]-angle>thr){
						motor[port2] = 110;
					}
					else if (SensorValue[p]-angle<-thr){
						motor[port2] = -110;
					}
				}
			}



		}

		//}

		if (punch == true){
			motor[port3] = -127;
		}
		else{
			motor[port3] = 0;
		}



		if (vexRT[Btn8U] == 1){
			motor[intake] = -127;
		}
		else if (vexRT[Btn8D] == 1){
			motor[intake] = 127;
		}
		else{
			motor[intake] = 0;
		}

		int a = -(vexRT[Ch3] + vexRT[Ch4]*0.8 + vexRT[Ch3Xmtr2] + vexRT[Ch4Xmtr2]*0.8);
		int b =  -(vexRT[Ch3]*-1+vexRT[Ch4]*0.8 + vexRT[Ch3Xmtr2]*-1+vexRT[Ch4Xmtr2]*0.8);
		if (vexRT[Btn8L]==1&&prestate1==0){
			if (ts==1) ts = 0;
			else ts = 1;
			prestate1 = 1;
		}
		if (vexRT[Btn8L] ==0 &&prestate1==1){
			prestate1 = 0;
		}
		if (ts==1){
			motor[port5] = a;


			motor[port6] = b;

		}
		else{
			motor[port5] = b;


			motor[port6] = a;
		}
		if (vexRT[Btn7U] == 1){
			motor[port7] = 127;
			wait1Msec(100);
	  }
		else if (vexRT[Btn7U] == 0){
			motor[port7] = 0;
	  }
	  if (vexRT[Btn7D] == 1){
	  	motor[port7] = - 127;
	  	wait1Msec(500);
	  }
	  else if (vexRT[Btn7D] == 1){
	  	motor[port7] = 0;
	  }
	}
}
