#pragma config(Motor,  port2,           Leftdrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Rightdrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           launcher12,    tmotorNone, openLoop)
#pragma config(Motor,  port6,           launcher3,     tmotorNone, openLoop)
#pragma config(Motor,  port7,           launcher4,     tmotorNone, openLoop)
#pragma config(Motor,  port8,           Arm,           tmotorNone, openLoop)
#pragma config(Motor,  port9,           Forearm,       tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int full_speed = 127;
	int full_speed_reverse = -127;
	int state=0, preState=0;

	while (true){

		motor[Leftdrive] = (vexRT[Ch3]*-1 + vexRT[Ch4]*-1);
		motor[Rightdrive] = (vexRT[Ch3] + vexRT[Ch4]*-1);

		//intake
		if (vexRT[Btn8D] == 1){
			//take in
			motor[Intake] = full_speed;
		}
		//flip
		if (vexRT[Btn8U] == 1){
			motor[Intake] = full_speed_reverse;
		}


		if (vexRT[Btn5D]==0){
				preState = 0;
		}
		if (vexRT[Btn5D] == 1 && preState ==0){
			preState = 1;
			state = state == 0? 1:0;
		}

		motor[launcher12] = state*127;
		motor[launcher3] = state*127;
		motor[launcher4] = state*127;

		motor[Arm] = vexRT[Ch2]*-1;

		if (vexRT[Btn7U] == 1){
			motor[Forearm] = 60;
		}else{
			motor[Forearm] = 0;
		}

		if (vexRT[Btn7D] == 1){
			motor[Forearm] = -60;
		}else{
			motor[Forearm] = 0;
		}
	}


}
