#pragma config(Motor,  port2,           Leftdrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Rightdrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           launcher12,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           launcher3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           launcher4,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           forearm,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*#pragma config(Sensor, dgtl1,  rightin,        sensorQuadEncoder)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           forearm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           launcher1,     tmotorVex393_MC29, openLoop)*/

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, dgtl1,  rightin,        sensorQuadEncoder)
//#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
//#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port4,           launcher1,     tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port6,           motor6,        tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)



//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//#pragma config(Motor,  port8,           arm_motor,     tmotorVex393_MC29, openLoop)
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	// This is the main execution loop for the user control program.
	// Each time through the loop your program should update motor + servo
	// values based on feedback from the joysticks.

	// ........................................................................
	// Insert user code here. This is where you use the joystick values to
	// update your motors, etc.
	// ........................................................................

	int state=0, preState=0;
	int ts = 1, prestate1 = 0;

	//int initial_sensor = SensorValue[rightin];
	while(1==1){
		//DRIVING///////////////////////////////////////////////////////////////////
		int a = -(vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch3Xmtr2] + vexRT[Ch4Xmtr2]);
		int b =  -(vexRT[Ch3]*-1 + vexRT[Ch4] + vexRT[Ch3Xmtr2]*-1 + vexRT[Ch4Xmtr2]);
		if (vexRT[Btn8L]==1&&prestate1==0){
			if (ts==1) ts = 0;
			else ts = 1;
			prestate1 = 1;
		}
		if (vexRT[Btn8L] ==0 &&prestate1==1){
			prestate1 = 0;
		}
		if (ts==1){
			motor[Leftdrive] = a;

			motor[Rightdrive] = b;

		}
		else{
			motor[Leftdrive] = b;

			motor[Rightdrive] = a;

		}



		//port 4 connected to motor 7 and 8
		//port 5 connected to motor 9 and 10
		if (vexRT[Btn5D]==0){
			preState = 0;
		}

		if (vexRT[Btn5D] == 1 && preState ==0){
			preState = 1;
			state = state == 0? 1:0;
		}
		motor[launcher12] = state*127;
		motor[launcher3] = state*127;
		motor[launcher4] = state*127;


		//motor[port6] = vexRT[Btn8D]==1? -127:0;
		//motor[port6] = vexRT[Btn8U]==1? 127:0;
		motor[Intake] = 0;
		if (vexRT[Btn8U] == 1){
			motor[Intake] = -127;
		}

		//sauce thing flipper
		if (vexRT[Btn8D] == 1){
			motor[Intake] = 127;

		}





		motor[arm] = -vexRT[Ch2];



		motor[forearm] = -12;
		if (vexRT[Btn7U] == 1){
			motor[forearm] = -127;
		}

		//sauce thing flipper
		if (vexRT[Btn7D] == 1){
			motor[forearm] = 127;

		}


		//motor[forearm] = -vexRT[Ch2]-15;


	}

}
