#pragma config(Sensor, dgtl1,  rightin,        sensorQuadEncoder)
#pragma config(Motor,  port2,           leftfront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftback,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightfront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightback,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           forearm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           launcher1,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// for each process n, there are pnSpeed and pnTime, for the motor power and wait time respectively
	int p1Speed = 100, p1Time = 100, p2Speed = 100, p2Time = 100, p4Speed = 100, p4Time = 100, p5Speed = 100, p5Time = 100;
	while (true)
	{

		//process 1: go front straight
		motor[leftfront] = p1Speed;
		motor[leftback] = p1Speed;
		motor[rightfront] = - p1Speed;
		motor[rightback] = - p1Speed;
		wait(p1Time);
		//process 2: pick up ball while moving forward
		motor[intake] = p2Speed;
		wait(p2Time);
		motor[leftfront] = 0;
		motor[leftback] = 0;
		motor[rightfront] = 0;
		motor[rightback] = 0;
		motor[intake] = 0;

		//process 3: go back to starting point
			//p3 speed and time should be same as p1
		motor[leftfront] = -p1Speed;
		motor[leftback] = -p1Speed;
		motor[rightfront] = p1Speed;
		motor[rightback] = p1Speed;
		wait(p1Time);
		motor[leftfront] = 0;
		motor[leftback] = 0;
		motor[rightfront] = 0;
		motor[rightback] = 0;
		//process 4: rotate 90 counterclockwise
		motor[leftfront] = - p4Speed;
		motor[leftback] = - p4Speed;
		motor[rightfront] = p4Speed;
		motor[rightback] = p4Speed;
		wait(p4Time);
		motor[leftfront] = 0;
		motor[leftback] = 0;
		motor[rightfront] = 0;
		motor[rightback] = 0;
		//process 5: go front a distance and shoot
		motor[leftfront] = p5Speed;
		motor[leftback] = p5Speed;
		motor[rightfront] = - p5Speed;
		motor[rightback] = - p5Speed;
		wait(p1Time);
	}

}
